from .face_aligned_center import (
    NODE_CLASS_MAPPINGS as _CENTER_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CENTER_NAMES,
)
from .face_aligned_fine_tune import (
    NODE_CLASS_MAPPINGS as _TUNE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _TUNE_NAMES,
)
from .anime_face_detect import (
    NODE_CLASS_MAPPINGS as _FACE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _FACE_NAMES,
)

NODE_CLASS_MAPPINGS = {**_CENTER_NODES, **_TUNE_NODES, **_FACE_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_CENTER_NAMES, **_TUNE_NAMES, **_FACE_NAMES}
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
